version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: quangnm1999/reverseproxy
  backend-user:
    build:
      context: ./udagram-api-user
    image: quangnm1999/udagram-api-user
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: quangnm1999/udagram-api-feed
  udagram-frontend:
    build:
      context: ./udagram-frontend
    image: quangnm1999/udagram-frontend