version: 2.1

jobs:
  init-microservices-application:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container
          command: |
            echo "--------- Building ------------"

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed quangnm1999/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user quangnm1999/udagram-api-user:v1
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend quangnm1999/udagram-frontend:v1

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy quangnm1999/reverseproxy:v1

            echo "-------- All images succesfully built----------"

            echo " ------- login in to hub--------"

            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            echo "-------------- Pushing images to dockerhub-------"
            
            docker push quangnm1999/udagram-api-feed:v1
            docker push quangnm1999/udagram-api-user:v1
            docker push quangnm1999/udagram-frontend:v1
            docker push quangnm1999/reverseproxy:v1
workflows:
  default:
    jobs:
      - init-microservices-application
      - build-docker:
          requires: [init-microservices-application]