version: 2.1

jobs:
  int-application:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container
          command: |
            echo "--------- Building Image ------------"

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed quangnm1999/udagram-api-feed:latest

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user quangnm1999/udagram-api-user:latest
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend quangnm1999/udagram-frontend:latest

            docker build -t reverseproxy ./udagram-reverseproxy
            docker tag reverseproxy quangnm1999/reverseproxy:latest

            echo "-------- All images succesfully----------"

            echo " ------- login in to hub--------"

            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            echo "-------------- Pushing images to dockerhub-------"
            
            docker push quangnm1999/udagram-api-feed:latest
            docker push quangnm1999/udagram-api-user:latest
            docker push quangnm1999/udagram-frontend:latest
            docker push quangnm1999/reverseproxy:latest
workflows:
  default:
    jobs:
      - int-application
      - build-docker:
          requires: [int-application]